In [1]:
from dask.array import from_array
from numpy import array

A = array(range(36)).reshape((6,6))
d = from_array(A, chunks=(3,3))
d

dask.array<array, shape=(6, 6), dtype=int64, chunksize=(3, 3), chunktype=numpy.ndarray>

In [2]:
from scipy.sparse import spmatrix, coo_matrix, csr_matrix, csc_matrix, dia_matrix

sps = d.map_blocks(coo_matrix, chunks=(3,3))
sps.compute(scheduler="synchronous")

<6x6 sparse matrix of type '<class 'numpy.longlong'>'
	with 35 stored elements in COOrdinate format>

In [3]:
sps.compute().todense()

matrix([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]], dtype=int64)

In [4]:
d.sum().compute()

630

In [5]:
sps.sum().compute()

matrix([[630]])

In [6]:
d.sum(axis=1).compute()

array([ 15,  51,  87, 123, 159, 195])

In [7]:
sps.sum(axis=1).compute()

matrix([[ 15],
        [ 51],
        [ 87],
        [123],
        [159],
        [195]])

In [8]:
from numpy import matrix
mats = d.map_blocks(matrix, chunks=(3,3))
mats.sum().compute()

matrix([[630]])